# Generated by Django 3.0.3 on 2020-02-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolutionChainId', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('height', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseStat', models.CharField(default='', max_length=100)),
                ('effort', models.CharField(default='', max_length=100)),
                ('pokemon', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='StatsPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.URLField(default='', max_length=100)),
                ('stat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokemon.StatElement')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='evolution',
            name='pokemon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon'),
        ),
    ]
